services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: simple_parking
      POSTGRES_USER: simple_parking
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  simpleparking.api:
    image: simpleparking.api
    build:
      context: .
      dockerfile: SimpleParking.Api/Dockerfile
    depends_on:
      - db
volumes:
  db_data: