services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: simple_parking
      POSTGRES_USER: simple_parking
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
