@baseUrl = http://localhost:5000

###
# @name getAllVehicles
GET {{baseUrl}}/api/v1/vehicles
Accept: application/json

> {%
    client.global.set("vehicleId", response.body[0].id)
%}

###
# @name getVehicleById
GET {{baseUrl}}/api/v1/vehicles/{{vehicleId}}
Accept: application/json

###
# @name storeVehicle
POST {{baseUrl}}/api/v1/vehicles
Accept: application/json
Content-Type: application/json

{
  "brand": "Tesla",
  "model": "Cybertruck",
  "color": "Satin Stealth Black",
  "plate": "8ABC123",
  "type": "MOTORCYCLE"
}

###
# @name updateVehicleById
PUT {{baseUrl}}/api/v1/vehicles/{{vehicleId}}
Accept: application/json
Content-Type: application/json

{
  "brand": "Tesla",
  "model": "Cybertruck",
  "color": "Satin Stealth Black",
  "plate": "BAC0123",
  "type": "car"
}

###
# @name deleteVehicleById
DELETE {{baseUrl}}/api/v1/vehicles/{{vehicleId}}
Accept: application/json

###
# @name getAllEstablishments
GET {{baseUrl}}/api/v1/establishments
Accept: application/json

> {%
    client.global.set("establishmentId", response.body[0].id)
%}

###
# @name getEstablishmentById
GET {{baseUrl}}/api/v1/establishments/{{establishmentId}}
Accept: application/json

###
# @name storeEstablishment
POST {{baseUrl}}/api/v1/establishments
Accept: application/json
Content-Type: application/json

{
  "name": "Sherlock Parking",
  "cnpj": "58547301000110",
  "address": "Baker Street 221",
  "motorcycleParkingSpaces": 12,
  "carParkingSpaces": 20
}

###
# @name updateEstablishmentById
PUT {{baseUrl}}/api/v1/establishments/{{establishmentId}}
Accept: application/json
Content-Type: application/json

{
  "name": "Sherlock Parking",
  "cnpj": "58547301000110",
  "address": "Baker Street 221",
  "motorcycleParkingSpaces": 15,
  "carParkingSpaces": 69
}

###
# @name deleteEstablishmentById
DELETE {{baseUrl}}/api/v1/establishments/{{establishmentId}}
Accept: application/json
